import os

Import("env")

def generate_secrets_header(source, target, env):
    print("Generating secrets.h from .env...")
    
    dotenv_path = os.path.join(env.get("PROJECT_DIR"), ".env")
    secrets_path = os.path.join(env.get("PROJECT_INCLUDE_DIR"), "secrets.h")
    
    if not os.path.exists(dotenv_path):
        print(f"Warning: {dotenv_path} not found. build might fail if secrets are missing.")
        return

    with open(dotenv_path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    with open(secrets_path, "w", encoding="utf-8") as f:
        f.write("// Autogenerated by generate_secrets.py\n")
        f.write("#pragma once\n\n")
        for line in lines:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            
            if "=" in line:
                key, value = line.split("=", 1)
                key = key.strip()
                value = value.strip()
                # Ensure string values are quoted if they aren't already
                if not (value.startswith('"') and value.endswith('"')) and not (value.startswith("'") and value.endswith("'")):
                     # heuristic: if it looks like a number, don't quote, otherwise quote? 
                     # For safety in C defines usually string literals are needed for things like SSID.
                     # But some might be integers.
                     # Let's assume for now if it's WIFI related it's a string.
                     # Or better, just rely on the user to quote in .env? 
                     # Common convention is .env values are strings.
                     # Let's try to be smart: always quote unless it's clearly a number or boolean?
                     # Actually, for C macros, #define KEY "VALUE" is what we want for strings.
                     # Let's just wrap everything in quotes if it's not already wrapped.
                     # Wait, if it is a number like PORT=80, #define PORT "80" might be wrong if code expects int.
                     # Let's stick to simple text substitution but ensure string-like behavior requires quotes in .env or we add them.
                     pass

                # Simple approach: If the user provides WIFI_SSID=MyWifi, we make #define WIFI_SSID "MyWifi"
                # If they provide PIN=2, we make #define PIN 2
                # But .env parsers usually treat everything as string.
                # Let's force quotes for now as the user specifically asked for "sensible daten" which are usually strings (wifi, tokens).
                # If the value is not quoted, we quote it.
                if not (value.startswith('"') and value.endswith('"')):
                    value = f'"{value}"'
                
                f.write(f"#define {key} {value}\n")
    
    print(f"Successfully generated {secrets_path}")

# Run the function
generate_secrets_header(None, None, env)
